# Generated by Django 5.0.1 on 2024-02-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []                            # параметр, показывающий от чего зависела моя миграция 

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('auction', models.BooleanField(help_text='Отметьте, если торг будет уместен', verbose_name='Торг')),
                ('crated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('apdated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
        ),
    ]
