# Generated by Django 5.0.1 on 2024-02-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisement',
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
